// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AddGameToCollection(arg1:main.LocatedGame,arg2:string):Promise<void>;

export function ApplyPatch(arg1:main.GameInfo,arg2:main.PatchInfo,arg3:boolean,arg4:boolean):Promise<void>;

export function DownloadPatch(arg1:string):Promise<main.PatchInfo>;

export function FetchAllPatches():Promise<Array<main.PatchEntry>>;

export function GetGameInfoFromExePath(arg1:string):Promise<main.GameInfo>;

export function GetGamesCollection():Promise<Array<main.LocatedGame>>;

export function LaunchGameFromPath(arg1:string):Promise<void>;

export function Log(arg1:string):Promise<void>;

export function LogError(arg1:string):Promise<void>;

export function LogSuccess(arg1:string):Promise<void>;

export function OpenFolder(arg1:string):Promise<void>;

export function PrepareGameToAddToCollection():Promise<main.LocatedGame>;

export function RemoveGameFromCollection(arg1:string):Promise<void>;

export function RestoreGameBackup(arg1:main.GameInfo):Promise<void>;

export function SelectGameExeFile():Promise<main.GameInfo>;

export function SelectPatchFile():Promise<main.PatchInfo>;

export function SetGameTranslated(arg1:string,arg2:boolean):Promise<void>;
