// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {domain} from '../models';

export function AddGameToCollection(arg1:domain.LocatedGame,arg2:string,arg3:string,arg4:Array<string>):Promise<void>;

export function ApplyPatch(arg1:domain.GameInfo,arg2:domain.PatchInfo,arg3:boolean,arg4:boolean):Promise<void>;

export function ApplyUpdate():Promise<void>;

export function CheckForUpdate():Promise<domain.ReleaseInfo>;

export function DeletePersistentData():Promise<void>;

export function DownloadPatch(arg1:string):Promise<domain.PatchInfo>;

export function DownloadUpdate(arg1:domain.ReleaseInfo):Promise<void>;

export function ExportPatchedFiles(arg1:string,arg2:string):Promise<void>;

export function FetchAllPatches():Promise<Array<domain.PatchEntry>>;

export function GetCurrentVersion():Promise<number>;

export function GetGameInfoFromExePath(arg1:string):Promise<domain.GameInfo>;

export function GetGamesCollection():Promise<Array<domain.LocatedGame>>;

export function GetGamesPerRow():Promise<number>;

export function GetLatestReleaseInfo():Promise<domain.ReleaseInfo>;

export function GetPersistentDataPath():Promise<string>;

export function LaunchGameFromPath(arg1:string):Promise<void>;

export function Log(arg1:string):Promise<void>;

export function LogError(arg1:string):Promise<void>;

export function LogSuccess(arg1:string):Promise<void>;

export function OpenFolder(arg1:string):Promise<void>;

export function PrepareGameToAddToCollection():Promise<domain.LocatedGame>;

export function RemoveGameFromCollection(arg1:string):Promise<void>;

export function RestoreGameBackup(arg1:domain.GameInfo):Promise<void>;

export function SelectGameExeFile():Promise<domain.GameInfo>;

export function SelectPatchFile():Promise<domain.PatchInfo>;

export function SetGamePinned(arg1:string,arg2:boolean):Promise<void>;

export function SetGamePlayStatus(arg1:string,arg2:string):Promise<void>;

export function SetGameTranslated(arg1:string,arg2:boolean):Promise<void>;

export function SetGamesPerRow(arg1:number):Promise<void>;

export function UpdateGameMetadata(arg1:string,arg2:string,arg3:Array<string>):Promise<void>;
