// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ApplyPatch(arg1, arg2) {
  return window['go']['main']['App']['ApplyPatch'](arg1, arg2);
}

export function Log(arg1) {
  return window['go']['main']['App']['Log'](arg1);
}

export function LogError(arg1) {
  return window['go']['main']['App']['LogError'](arg1);
}

export function LogSuccess(arg1) {
  return window['go']['main']['App']['LogSuccess'](arg1);
}

export function SelectGameExeFile() {
  return window['go']['main']['App']['SelectGameExeFile']();
}

export function SelectPatchFile() {
  return window['go']['main']['App']['SelectPatchFile']();
}
