// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddGameToCollection(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['AddGameToCollection'](arg1, arg2, arg3, arg4);
}

export function ApplyPatch(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['ApplyPatch'](arg1, arg2, arg3, arg4);
}

export function ApplyUpdate() {
  return window['go']['main']['App']['ApplyUpdate']();
}

export function CheckForUpdate() {
  return window['go']['main']['App']['CheckForUpdate']();
}

export function DeletePersistentData() {
  return window['go']['main']['App']['DeletePersistentData']();
}

export function DownloadPatch(arg1) {
  return window['go']['main']['App']['DownloadPatch'](arg1);
}

export function DownloadUpdate(arg1) {
  return window['go']['main']['App']['DownloadUpdate'](arg1);
}

export function ExportPatchedFiles(arg1, arg2) {
  return window['go']['main']['App']['ExportPatchedFiles'](arg1, arg2);
}

export function FetchAllPatches() {
  return window['go']['main']['App']['FetchAllPatches']();
}

export function GetCurrentVersion() {
  return window['go']['main']['App']['GetCurrentVersion']();
}

export function GetGameInfoFromExePath(arg1) {
  return window['go']['main']['App']['GetGameInfoFromExePath'](arg1);
}

export function GetGamesCollection() {
  return window['go']['main']['App']['GetGamesCollection']();
}

export function GetGamesPerRow() {
  return window['go']['main']['App']['GetGamesPerRow']();
}

export function GetLatestReleaseInfo() {
  return window['go']['main']['App']['GetLatestReleaseInfo']();
}

export function GetPersistentDataPath() {
  return window['go']['main']['App']['GetPersistentDataPath']();
}

export function LaunchGameFromPath(arg1) {
  return window['go']['main']['App']['LaunchGameFromPath'](arg1);
}

export function Log(arg1) {
  return window['go']['main']['App']['Log'](arg1);
}

export function LogError(arg1) {
  return window['go']['main']['App']['LogError'](arg1);
}

export function LogSuccess(arg1) {
  return window['go']['main']['App']['LogSuccess'](arg1);
}

export function OpenFolder(arg1) {
  return window['go']['main']['App']['OpenFolder'](arg1);
}

export function PrepareGameToAddToCollection() {
  return window['go']['main']['App']['PrepareGameToAddToCollection']();
}

export function RemoveGameFromCollection(arg1) {
  return window['go']['main']['App']['RemoveGameFromCollection'](arg1);
}

export function RestoreGameBackup(arg1) {
  return window['go']['main']['App']['RestoreGameBackup'](arg1);
}

export function SelectGameExeFile() {
  return window['go']['main']['App']['SelectGameExeFile']();
}

export function SelectPatchFile() {
  return window['go']['main']['App']['SelectPatchFile']();
}

export function SetGamePinned(arg1, arg2) {
  return window['go']['main']['App']['SetGamePinned'](arg1, arg2);
}

export function SetGamePlayStatus(arg1, arg2) {
  return window['go']['main']['App']['SetGamePlayStatus'](arg1, arg2);
}

export function SetGameTranslated(arg1, arg2) {
  return window['go']['main']['App']['SetGameTranslated'](arg1, arg2);
}

export function SetGamesPerRow(arg1) {
  return window['go']['main']['App']['SetGamesPerRow'](arg1);
}

export function UpdateGameMetadata(arg1, arg2, arg3) {
  return window['go']['main']['App']['UpdateGameMetadata'](arg1, arg2, arg3);
}
