// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function ApplyPatch(arg1:main.GameInfo,arg2:main.PatchInfo):Promise<void>;

export function Log(arg1:string):Promise<void>;

export function LogError(arg1:string):Promise<void>;

export function LogSuccess(arg1:string):Promise<void>;

export function SelectGameExeFile():Promise<main.GameInfo>;

export function SelectPatchFile():Promise<main.PatchInfo>;
