// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddGameToCollection(arg1, arg2) {
  return window['go']['main']['App']['AddGameToCollection'](arg1, arg2);
}

export function ApplyPatch(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['ApplyPatch'](arg1, arg2, arg3, arg4);
}

export function DownloadPatch(arg1) {
  return window['go']['main']['App']['DownloadPatch'](arg1);
}

export function FetchAllPatches() {
  return window['go']['main']['App']['FetchAllPatches']();
}

export function GetGameInfoFromExePath(arg1) {
  return window['go']['main']['App']['GetGameInfoFromExePath'](arg1);
}

export function GetGamesCollection() {
  return window['go']['main']['App']['GetGamesCollection']();
}

export function LaunchGameFromPath(arg1) {
  return window['go']['main']['App']['LaunchGameFromPath'](arg1);
}

export function Log(arg1) {
  return window['go']['main']['App']['Log'](arg1);
}

export function LogError(arg1) {
  return window['go']['main']['App']['LogError'](arg1);
}

export function LogSuccess(arg1) {
  return window['go']['main']['App']['LogSuccess'](arg1);
}

export function OpenFolder(arg1) {
  return window['go']['main']['App']['OpenFolder'](arg1);
}

export function PrepareGameToAddToCollection() {
  return window['go']['main']['App']['PrepareGameToAddToCollection']();
}

export function RemoveGameFromCollection(arg1) {
  return window['go']['main']['App']['RemoveGameFromCollection'](arg1);
}

export function RestoreGameBackup(arg1) {
  return window['go']['main']['App']['RestoreGameBackup'](arg1);
}

export function SelectGameExeFile() {
  return window['go']['main']['App']['SelectGameExeFile']();
}

export function SelectPatchFile() {
  return window['go']['main']['App']['SelectPatchFile']();
}

export function SetGameTranslated(arg1, arg2) {
  return window['go']['main']['App']['SetGameTranslated'](arg1, arg2);
}
